name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - 'lab1/producer/producer.py'

jobs:
  editorconfig-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: EditorConfig Check
        run: |
          npx editorconfig-checker

  build-and-deploy:
    runs-on: ubuntu-latest

    needs: [editorconfig-check]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS2 }}

      - name: Azure Container Registry Login
        run: az acr login --name lab1reg.azurecr.io

      - name: Docker Image Build and Push to ACR
        run: |
          docker build -t lab1reg.azurecr.io/producer:latest lab1/producer
          docker push lab1reg.azurecr.io/producer:latest

      - name: Build and deploy Container App
        run: az containerapp create --resource-group fervjestina --environment fervjestina-ca-env --name producer-ca --image lab1reg.azurecr.io/producer:latest
