name: Docker Image CI

on:
  push:
    branches: "main" 
    paths:
      - 'lab1/producer/producer.py'
  pull_request:
    branches: "main"
    paths:
      - 'lab1/producer/producer.py'

jobs:
  editorconfig-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: EditorConfig Check
      run: |
        npx editorconfig-checker

  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Super-Linter
      uses: super-linter/super-linter@v5.6.1
         
  build-and-deploy:
    runs-on: ubuntu-latest

    needs: [editorconfig-check, linter]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build Docker image
      run: |
        docker build -t producer:latest .
      # Prilagodite ovo svojim stvarnim naredbama za izgradnju Docker slike

    - name: Push Docker image to Azure Container Registry (ACR)
      run: |
        docker tag producer:latest lab1reg.azurecr.io/producer:latest
        docker login lab1reg.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
        docker push lab1reg.azurecr.io/producer:latest

    - name: Deploy to Azure Container Apps
      run: |
        az containerapp create --name producer --resource-group myrg --image lab1reg.azurecr.io/producer:latest
      # Prilagodite ovo svojim stvarnim naredbama za postavljanje slike na Azure Container Apps
